### ISSUE TITLE
Heroku - 

### ISSUE THREAD

**Issue by FlowQ** [nothingisdead/npm-kraken-api#40]
When I use the module locally everything is fine but when used on Heroku I get the following error: 
> 2017-08-11T10:34:14.648559+00:00 app[web.1]: /app/node_modules/kraken-api/kraken.js:31
> 2017-08-11T10:34:14.648573+00:00 app[web.1]: const rawRequest = async (url, headers, data, timeout) => {
> 2017-08-11T10:34:14.648575+00:00 app[web.1]: 
> 2017-08-11T10:34:14.648575+00:00 app[web.1]: SyntaxError: Unexpected token (
> 2017-08-11T10:34:14.648576+00:00 app[web.1]:     at createScript (vm.js:56:10)
> 2017-08-11T10:34:14.648576+00:00 app[web.1]:     at Object.runInThisContext (vm.js:97:10)
> 2017-08-11T10:34:14.648577+00:00 app[web.1]:     at Module._compile (module.js:542:28)
> 2017-08-11T10:34:14.648578+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
> 2017-08-11T10:34:14.648578+00:00 app[web.1]:     at Module.load (module.js:487:32)
> 2017-08-11T10:34:14.648579+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
> 2017-08-11T10:34:14.648580+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
> 2017-08-11T10:34:14.648580+00:00 app[web.1]:     at Module.require (module.js:497:17)
> 2017-08-11T10:34:14.648581+00:00 app[web.1]:     at require (internal/module.js:20:19)
> 2017-08-11T10:34:14.648582+00:00 app[web.1]:     at Object.<anonymous (/app/bin/krakenBalances.js:1:84)

The corresponding code line generating the error is just the loading of the package:
`const KrakenClient = require('kraken-api');`

Do you have any suggestion ? 

Thank you for your help

**Comment by mlaigre** [comment]
Problem solved here by updating node to 8.4.
