### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Vigor111** [nothingisdead/npm-kraken-api#45]
when I import the `kraken-api` and run the project.
I get this error.
```
const rawRequest = async (url, headers, data, timeout) => {
                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Work/SourceTree/financial/dist/market/Kraken.js:11:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Work/SourceTree/financial/dist/test.js:17:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by kroitor** [comment]
@Vigor111 you probably have an old version of node. Try `node --version` in console, and if it shows less then current stable (8+), update it, then retry the code.

**Comment by Vigor111** [comment]
Oh it works, Thanks for your advice..
+1

**Comment by shahinfir** [comment]
I have v9.3.0 and I still get this same error. Any ideas?

**Comment by SandeshSarfare** [comment]
@shahinfir  did you resolve it? I too have the same error
